#!/usr/bin/env perl
use v5.14;
use strict;
use FindBin;
BEGIN {
    unshift @INC, "$FindBin::Bin/../../local/lib";
    unshift @INC, "$FindBin::Bin/../../lib";
    unshift @INC, "$FindBin::Bin/../lib";
}

use G0cr::ElasticSearch;

my $es = G0cr::ElasticSearch->new;

$es->create_index;
